server:
  affinity: ""
  ha:
    enabled: true
    replicas: 3
    config: |
      ui = true
      disable_mlock = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }

      backend "consul" {
        path = "vault/"
        address = "consul-server.consul:8500"
      }
